# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insapp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 283)
        MainWindow.setMaximumSize(QtCore.QSize(367, 283))
        MainWindow.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 232, 279, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"font: 12pt \"STKaiti\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"padding-left:1px;\n"
"padding-top:1px;\n"
"background-color: rgba(168, 195, 134,240)}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.printwin = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.printwin.setGeometry(QtCore.QRect(8, 5, 351, 251))
        self.printwin.setStyleSheet("background-color: rgb(238, 218, 143) ;\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 8pt \"Times\";")
        self.printwin.setReadOnly(True)
        self.printwin.setPlainText("")
        self.printwin.setObjectName("printwin")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 321, 221))
        self.groupBox.setStyleSheet("font: 87 9pt \"Arial Black\";\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 281, 178))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setStyleSheet("font: 8pt \"STKaiti\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setStyleSheet("font: 8pt \"STKaiti\";")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font: 25 12pt \"STFangsong\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("font: 25 12pt \"STFangsong\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setStyleSheet("font: 8pt \"STKaiti\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setStyleSheet("font: 8pt \"STKaiti\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setStyleSheet("font: 8pt \"STKaiti\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("font: 25 12pt \"STFangsong\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_3.setStyleSheet("font: 25 12pt \"STFangsong\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_2.setStyleSheet("font: 25 12pt \"STFangsong\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 25 12pt \"STFangsong\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 230, 113, 21))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"   background-color: rgba(212, 101, 62,200);\n"
"  border:none;\n"
"   color: rgb(255, 255, 255);\n"
"   border-radius:10px\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.disp_contrast_time = QtWidgets.QLabel(self.centralwidget)
        self.disp_contrast_time.setGeometry(QtCore.QRect(20, 240, 201, 16))
        self.disp_contrast_time.setStyleSheet("font: 75 7pt \"Times New Roman\";\n"
"background-color: rgba(238, 218, 143,200) ;")
        self.disp_contrast_time.setText("")
        self.disp_contrast_time.setObjectName("disp_contrast_time")
        self.printwin.raise_()
        self.pushButton.raise_()
        self.groupBox.raise_()
        self.pushButton_2.raise_()
        self.disp_contrast_time.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "提   交"))
        self.groupBox.setTitle(_translate("MainWindow", "INPUT INFORMATION"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "例 巴啦啦课题组"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "AES加密密码"))
        self.label_6.setText(_translate("MainWindow", "课 题 组 名"))
        self.label_5.setText(_translate("MainWindow", "预 约 时 间"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "例：06:00:00"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "LCMSMS直接输入，其他查阅网页"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "预约?天后,例：14"))
        self.label_4.setText(_translate("MainWindow", "预 约 日 期"))
        self.label_3.setStatusTip(_translate("MainWindow", "同密码获取方式类似"))
        self.label_3.setWhatsThis(_translate("MainWindow", "同密码获取方式类似"))
        self.label_3.setText(_translate("MainWindow", "仪 器 编 码"))
        self.label_2.setStatusTip(_translate("MainWindow", "加密密码获取需打开网页，F12后获取post信息"))
        self.label_2.setWhatsThis(_translate("MainWindow", "加密密码获取需打开网页，F12后获取post信息"))
        self.label_2.setText(_translate("MainWindow", "密          码"))
        self.label.setText(_translate("MainWindow", "登 录 名 称"))
        self.pushButton_2.setText(_translate("MainWindow", "返回"))
